// districts.js

const statesAndDistricts = {
  "Tamil Nadu": [
    "Ariyalur",
    "Chengalpattu",
    "Chennai",
    "Coimbatore",
    "Cuddalore",
    "Dharmapuri",
    "Dindigul",
    "Erode",
    "Kallakurichi",
    "Kanchipuram",
    "Karur",
    "Krishnagiri",
    "Madurai",
    "Mayiladuthurai",
    "Nagapattinam",
    "Namakkal",
    "Nilgiris",
    "Perambalur",
    "Pudukkottai",
    "Ramanathapuram",
    "Ranipet",
    "Salem",
    "Sivaganga",
    "Tenkasi",
    "Thanjavur",
    "Theni",
    "Thoothukudi",
    "Tiruchirappalli",
    "Tirunelveli",
    "Tirupathur",
    "Tiruppur",
    "Tiruvallur",
    "Tiruvannamalai",
    "Tiruvarur",
    "Vellore",
    "Viluppuram",
    "Virudhunagar",
  ],

  Kerala: [
    "Thiruvananthapuram",
    "Kollam",
    "Pathanamthitta",
    "Alappuzha",
    "Kottayam",
    "Idukki",
    "Ernakulam",
    "Thrissur",
    "Palakkad",
    "Malappuram",
    "Kozhikode",
    "Wayanad",
    "Kannur",
    "Kasaragod",
  ],

  Karnataka: [
    "Bengaluru Urban",
    "Bengaluru Rural",
    "Mysuru",
    "Mandya",
    "Mangalore",
    "Hubli",
    "Belagavi",
    "Davangere",
    "Tumakuru",
    "Shivamogga",
    "Hassan",
    "Ballari",
    "Raichur",
    "Bidar",
    "Kalaburagi",
  ],

  Maharashtra: [
    "Mumbai City",
    "Mumbai Suburban",
    "Pune",
    "Nagpur",
    "Nashik",
    "Aurangabad",
    "Kolhapur",
    "Thane",
    "Satara",
    "Solapur",
    "Ratnagiri",
    "Sangli",
    "Wardha",
  ],

  "Uttar Pradesh": [
    "Agra",
    "Lucknow",
    "Kanpur",
    "Varanasi",
    "Prayagraj",
    "Meerut",
    "Noida",
    "Ghaziabad",
    "Aligarh",
    "Bareilly",
    "Gorakhpur",
    "Jhansi",
    "Ballia",
    "Ayodhya",
  ],

  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Darjeeling",
    "Siliguri",
    "Durgapur",
    "Asansol",
    "Birbhum",
    "South 24 Parganas",
    "North 24 Parganas",
    "Murshidabad",
  ],

  Bihar: [
    "Patna",
    "Nalanda",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Darbhanga",
    "Munger",
    "Siwan",
    "Aurangabad",
    "Saharsa",
    "Begusarai",
  ],

  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Nellore",
    "Kadapa",
    "Kurnool",
    "Anantapur",
    "Tirupati",
    "Ongole",
    "Srikakulam",
    "Rajahmundry",
  ],

  Rajasthan: [
    "Jaipur",
    "Udaipur",
    "Jodhpur",
    "Ajmer",
    "Kota",
    "Bikaner",
    "Alwar",
    "Bharatpur",
    "Pali",
    "Nagaur",
  ],

  Punjab: [
    "Amritsar",
    "Ludhiana",
    "Patiala",
    "Jalandhar",
    "Mohali",
    "Pathankot",
    "Moga",
    "Hoshiarpur",
    "Bathinda",
  ],
};
